# Generated by Django 3.0.8 on 2020-07-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=20)),
                ('course_number', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('grade', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisite',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prereq1', models.IntegerField()),
                ('prereq2', models.IntegerField()),
            ],
        ),
    ]
